### ISSUE TITLE
Парсер выдает не все пары

### ISSUE THREAD

**Issue by ysturasp** [YSTUty/ystuty-parser#4]
При запросе на группу ЦПИ-11 выдает расписание на некоторые недели, а вот, например, на 2 и 3 расписания нет, хотя на сайте оно точно есть. Также подобное и с другими группами первого курса ицс при запросе на апи https://parser.ystuty.ru/api/ystu/schedule/group/{name_group}
 
Скриншот из сваггера
![CleanShot 2024-07-17 at 15 09 10](https://github.com/user-attachments/assets/53215edb-547c-4732-982c-95c394ad7470)

Скриншот расписания
![CleanShot 2024-07-17 at 15 07 20](https://github.com/user-attachments/assets/69edf138-bc42-4b36-b957-47629558a8d4)

**Comment by xTCry** [comment]
Данный сервис устарел и больше не поддерживается. 

Сейчас используется новый сервис -  https://github.com/YSTUty/ystuty-service-schedule

Адрес нового API - https://gg-api.ystuty.ru/s/schedule/swagger
